#include <Arduino.h>

const char* const BANKNAMES[] PROGMEM = {
"Acoustic Grand Piano",
"Bright Acoustic Piano",
"Electric Grand Piano",
"Honky-tonk Piano",
"Electric Piano 1",
"Electric Piano 2",
"Harpsichord",
"Clavi",
"Celesta",
"Glockenspiel",
"Music Box",
"Vibraphone",
"Marimba",
"Xylophone",
"Tubular Bells",
"Dulcimer",
"Drawbar Organ",
"Percussive Organ",
"Rock Organ",
"Church Organ",
"Reed Organ",
"Accordion",
"Harmonica",
"Tango Accordion",
"Acoustic Guitar (nylon)",
"Acoustic Guitar (steel)",
"Electric Guitar (jazz)",
"Electric Guitar (clean)",
"Electric Guitar (muted)",
"Overdriven Guitar",
"Distortion Guitar",
"Guitar Harmonics",
"Acoustic Bass",
"Electric Bass (finger)",
"Electric Bass (pick)",
"Fretless Bass",
"Slap Bass 1",
"Slap Bass 2",
"Synth Bass 1",
"Synth Bass 2",
"Violin",
"Viola",
"Cello",
"Contrabass",
"Tremolo Strings",
"Pizzicato Strings",
"Orchestral Harp",
"Timpani",
"String Ensembles 1",
"String Ensembles 2",
"Synth Strings 1",
"Synth Strings 2",
"Choir Aahs",
"Voice Oohs",
"Synth Voice",
"Orchestra Hit",
"Trumpet",
"Trombone",
"Tuba",
"Muted Trumpet",
"French Horn",
"Brass Section",
"Synth Brass 1",
"Synth Brass 2",
"Soprano Sax",
"Alto Sax",
"Tenor Sax",
"Baritone Sax",
"Oboe",
"English Horn",
"Bassoon",
"Clarinet",
"Piccolo",
"Flute",
"Recorder",
"Pan Flute",
"Blown Bottle",
"Shakuhachi",
"Whistle",
"Ocarina",
"Square Lead (Lead 1)",
"Saw Lead (Lead)",
"Calliope Lead (Lead 3)",
"Chiff Lead (Lead 4)",
"Charang Lead (Lead 5)",
"Voice Lead (Lead 6)",
"Fifths Lead (Lead 7)",
"Bass + Lead (Lead 8)",
"New Age (Pad 1)",
"Warm Pad (Pad 2)",
"Polysynth (Pad 3)",
"Choir (Pad 4)",
"Bowed (Pad 5)",
"Metallic (Pad 6)",
"Halo (Pad 7)",
"Sweep (Pad 8)",
"Rain (FX 1)",
"Sound Track (FX 2)",
"Crystal (FX 3)",
"Atmosphere (FX 4)",
"Brightness (FX 5)",
"Goblins (FX 6)",
"Echoes (FX 7)",
"Sci-fi (FX 8)",
"Sitar",
"Banjo",
"Shamisen",
"Koto",
"Kalimba",
"Bag Pipe",
"Fiddle",
"Shanai",
"Tinkle Bell",
"Agogo",
"Pitched Percussion",
"Woodblock",
"Taiko Drum",
"Melodic Tom",
"Synth Drum",
"Reverse Cymbal",
"Guitar Fret Noise",
"Breath Noise",
"Seashore",
"Bird Tweet",
"Telephone Ring",
"Helicopter",
"Applause",
"Gunshot",
};
